repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.6

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
        args: [
            --ignore, "E203,E501,W291,W503", 
            --max-line-length, "89", 
            --max-complexity, "18"
        ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    - id: bandit
      args: 
      - -s
      - B101,B108,B322,B404,B603
