repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--ignore-init-module-imports",
            "--remove-unused-variables",
          ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      args:
      - -s
      - B101,B108,B301,B403,B404,B601,B603,B607

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      additional_dependencies: [flake8-docstrings]
      args: [
        --ignore, "E203,E501,W291,W503,C901,D107,D102,D202,D205,D403",
        --max-line-length, "89", 
        --max-complexity, "18",
        --docstring-convention, "google",
        ]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3
        args: [--config, "pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    - id: mypy
      args: [--ignore-missing-imports]
