name: "Check Code Format"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 code-formatting:
  name: Check code formatting
  runs-on: ubuntu-20.04
  steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Black & Flake8
      run: pip install black==19.10b0 flake8==3.8.3

    - name: Run Black
      run: black --skip-string-normalization --config=pyproject.toml --check .
    
    - name: Run Flake8
      run: flake8 
        --max-line-length=89 
        --max-complexity=18 
        --ignore=E203,E731,E402,E501,W291,W503 
        .
